manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff # <-- 'inorichi' を 'badjeff' に変更
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver # <-- 問題のモジュール
      remote: badjeff # <-- 参照先を 'badjeff' に変更
      revision: main
  self:
    path: config
